== <head>

=== Overview
`<body>` 태그가 화면에 보여지는 콘텐츠를 다루고 있다면, `<head>` 태그는 `<body>` 태그의 내용이 어떻게 브라우저에 보여지는지에 대한 설정 정보를 다룹니다.

=== <!DOCTYPE>
``DOCTYPE``은 문서의 맨 앞에 작성해야 하며, HTML 문서 형식의 버전 정보를 나타냅니다. +
우리가 다룰 ``DOCTYPE``은 ``HTML 5``입니다.

* HTML 4.01 Strict DTD
[source,html]
----
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
----
* HTML 4.01 Transitional DTD
[source,html]
----
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
----
* HTML 4.01 Frameset DTD
[source,html]
----
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
----
* HTML 5
[source,html]
----
<!DOCTYPE html>
----

=== <title>
`<title>` 태그는 페이지의 제목을 나타냅니다.
이곳에 적은 문구는 브라우저의 제목 표시줄에 나타나며, html 문서의 필수 요소이기 때문에 `<title>` 태그가 없는 문서는 문법상 오류입니다.

=== <meta>
브라우저 및 검색 엔진의 로봇 등에게 메타 정보를 제공할 때 사용합니다. +
문서의 구조 표현에는 영향을 주지 않으며, 메타 정보에 대한 표준 목록이 없어 ``name``과 `content` 속성에 원하는 정보를 자유롭게 정의할 수 있습니다.

자주 사용하는 ``name``의 속성값으로는 ``subject``, ``title``, ``author``, ``keywords``, `viewport` 등이 있습니다.

==== charset
``<meta charset="utf-8">``과 같이 문서의 인코딩 방식을 지정합니다.
가끔 웹페이지의 글자가 깨진 것을 볼 수 있는데, 인코딩 설정을 하지 않았거나 잘못 지정한 경우가 대부분입니다.

==== viewport
``viewport``는 모바일(or 태블릿) 기기의 랜더링 방식을 지정하는 중요한 요소입니다.
``content``에는 ``width``, ``initial-scale``, ``maximum-scale``, ``minimum-scale``, ``user-scalable`` 등의 정보를 기입합니다.

=== <style>
`<style>` 태그는 화면에 보여지는 모든 태그의 스타일 설정을 갖고 있습니다.
``<style type="text/css>``와 같이 사용하며, DOCTYPE이 HTML 5일 경우 `type` 속성은 생략 가능합니다.

CSS를 외부 링크로 연결할 땐 ``<link rel="stylesheet" type="text/css" href="style.css">``와 같이 작성합니다.
