== <input>

=== type Attribute

==== type="text"
``<input type="text">``는 기본적인 텍스트 입력창입니다.

[source,html]
----
<input type="text">
----

`size` 속성을 추가하여 입력창의 크기를 지정할 수 있습니다.

[source,html]
----
<input type="text" size="50">
----

`maxlength` 속성을 추가하여 입력할 글자수를 제한할 수 있습니다.

[source,html]
----
<input type="text" size="50" maxlength="20">
----

`value` 속성에는 입력창의 기본값을 지정할 수 있습니다.

[source,html]
----
<input type="text" size="50" maxlength="20" value="sogoonii">
----

`readonly` 속성은 입력창의 내용을 수정할 수 없게 만듭니다.

[source,html]
----
<input type="text" size="50" maxlength="20" value="sogoonii" readonly>
----

`disabled` 속성은 입력창을 사용할 수 없게 만듭니다.

[source,html]
----
<input type="text" size="50" maxlength="20" value="sogoonii" disabled>
----

`placeholder` 속성에는 입력창의 내용이 비어있을 때 보여줄 문구를 지정합니다.

[source,html]
----
<input type="text" size="50" placeholder="아이디를 입력해 주세요.">
----

==== type="search"
``<input type="search">``는 내용을 입력할 경우 "삭제(X)" 버튼을 제공합니다. +
"삭제(X)" 버튼을 클릭하여 입력한 내용을 지울 수 있으며, 그 외 모든 속성은 ``<input type="text">``와 동일합니다.

[source,html]
----
<input type="search" size="50" maxlength="20" placeholder="아이디를 입력해 주세요.">
----

==== type="password"
``<input type="password">``은 입력한 내용을 볼 수 없게 합니다. +
"비밀번호"나 "주민번호" 등을 입력할 때 주로 사용합니다.

[source,html]
----
<input type="password" size="50" maxlength="20" placeholder="비밀번호를 입력해 주세요.">
----

==== type="radio"
``<input type="radio">``는 "라디오 버튼"이라고 부르며, 여러가지 옵션 중 하나를 선택하기 위해 사용합니다. +
``size``, ``maxlength``, ``placeholder``등의 속성은 사용할 수 없습니다.

[source,html]
----
<input type="radio" name="radio">
<input type="radio" name="radio">
<input type="radio" name="radio">
<input type="radio" name="radio">
----

``<input type="radio">``는 `name` 속성의 값이 같은 항목 중 한가지 옵션을 선택할 수 있습니다.

[source,html]
----
<input type="radio" name="radio1">
<input type="radio" name="radio1">
<input type="radio" name="radio1">
<input type="radio" name="radio1">

<input type="radio" name="radio2">
<input type="radio" name="radio2">
<input type="radio" name="radio2">
<input type="radio" name="radio2">
----

==== type="checkbox"
``<input type="checkbox">``는 "체크 박스"이라고 부르며, ``<input type="radio">``와는 달리 다수의 옵션을 선택할 수 있습니다.

[source,html]
----
<input type="checkbox" name="checkbox">
<input type="checkbox" name="checkbox">
<input type="checkbox" name="checkbox">
<input type="checkbox" name="checkbox">
----

==== type="file"
``<input type="file">``는 "파일첨부"를 위해 사용합니다. 게시물 작성 시 로컬 PC에 있는 파일을 첨부할 수 있습니다.

[source,html]
----
<input type="file">
----

`accept` 속성을 통해 첨부 파일의 형태를 제한할 수 있습니다. (예: `accept="image/*"` 속성을 추가하여 이미지 태그만 첨부하게 함) 

[source,html]
----
<input type="file" accept="image/*">
----

==== type="submit"
``<input type="submit">``은 ``<form>``의 정보를 전송하기 위해 사용합니다. +
`value` 속성에 값이 없을 경우 브라우저의 기본값이 출력됩니다.

[source,html]
----
<input type="submit">
<input type="submit" value="보내기">
----

==== type="reset"
``<input type="reset">``은 ``<form>``의 내용을 초기화 합니다. +
`<form>` 태그 내에 초기값이 있을 경우 원래의 값으로 되돌립니다. +
``<input type="submit">``와 마찬가지로 `value` 속성에 값이 없을 경우 브라우저의 기본값이 출력됩니다.

[source,html]
----
<input type="reset">
<input type="reset" value="초기화">
----

=== Etc.

==== <select>
`<select>` 태그는 여러가지 옵션 중 하나를 선택한다는 점에서 ``<input type="radio">``와 같은 목적을 갖습니다.

[source,html]
----
<select>
	<option>다음 옵션 중 하나를 선택하세요.</option>
	<option>옵션 1</option>
	<option>옵션 2</option>
	<option>옵션 3</option>
	<option>옵션 4</option>
	<option>옵션 5</option>
</select>
----

옵션은 `<option>` 태그를 사용하며, 여러개의 옵션을 ``<optgroup>``으로 묶을 수 있습니다.

[source,html]
----
<select>
	<option>다음 옵션 중 하나를 선택하세요.</option>
	<optgroup label="옵션 1">
		<option>옵션 1-1</option>
		<option>옵션 1-2</option>
		<option>옵션 1-3</option>
	</optgroup> 
	<optgroup label="옵션 2">
		<option>옵션 2-1</option>
		<option>옵션 2-2</option>
		<option>옵션 2-3</option>
	</optgroup> 
</select>
----

==== <textarea>
`<textarea>` 태그는 많은 양의 텍스트 정보를 입력하기 위해 사용합니다.

[source,html]
----
<textarea></textarea>
----

``cols``와 `rows` 속성을 이용하여 크기를 지정할 수 있습니다.

[source,html]
----
<textarea cols="50" rows="10"></textarea>
----

``placeholder``를 사용할 수 있으며, 기본값은 시작태그와 종료태그 사이에 적어줍니다.

[source,html]
----
<textarea cols="50" rows="10" placeholder="내용을 입력해주세요.">기본값은 이곳에 적어줍니다.</textarea>
----

==== <label>
`<label>` 태그는 폼요소를 감싸주어 사용성을 좋게합니다.

[source,html]
----
<label>아이디 <input type="text"></label>
<label>패스워드 <input type="password"></label>
----

폼요소를 감싸지 않을 경우엔 ``id``와 `for` 속성으로 연결해줍니다.

[source,html]
----
<label for="id">아이디</label>: <input type="text" id="id">
<label for="password">패스워드</label>: <input type="text" id="password">
통신사:
	<input type="radio" name="mobile" id="skt"> <label for="skt">SKT</label>
	<input type="radio" name="mobile" id="kt"> <label for="kt">KT</label>
	<input type="radio" name="mobile" id="lg"> <label for="lg">LG U+</label>
----
