:toc: right

== font

=== font-style
``font-style``은 글자의 기울임을 지정하는 속성입니다. +
``italic`` 속성값을 사용할 수 있으며, 기본값은 ``normal``입니다. +
기본값으로 ``italic`` 스타일이 적용된 태그에는 ``<em>``, ``<i>``, ``<address>``, `<cite>` 등이 있습니다.
[source,css]
----
{ font-style: italic | noraml; }
----

=== font-weight
``font-weight``는 글자의 두께를 지정하는 속성입니다. +
``bold`` 속성값을 사용할 수 있으며, 기본값은 ``normal``입니다. +
기본값으로 ``bold`` 스타일이 적용된 태그에는 ``<h1> ~ <h6>``, ``<strong>``, ``<b>``, `<th>` 등이 있습니다.
[source,css]
----
{ font-style: bold | noraml; }
----
NOTE: 간혹 ``font-weight``에 100부터 700(100 단위)의 속성값을 사용한 경우를 볼 수 있습니다. +
모든 브라우저에서 지원하는 것은 아니니 이 점을 참고하여 사용하시면 되겠습니다.

=== font-size
``font-size``는 화면에 보여지는 텍스트의 크기를 지정하는 속성입니다. +
단위는 ``px``과 ``em``을 주로 사용하며, ``pt``와 ``rem``단위를 사용할 수도 있습니다.
[source,css]
.px
----
{ font-size: 12px; }
----
[source,css]
.em
----
{ font-size: 1.2em; }
----
[source,css]
.pt
----
{ font-size: 12pt; }
----
[source,css]
.rem
----
{ font-size: 1.2rem; }
----
NOTE: ``em``과 `rem` 단위는 부모와의 관계에 따라 크기가 잘라질 수 있습니다. +
``pt``는 인쇄를 위한 단위이며, ``1pt``는 0.72inch 입니다. 또 ``px``과 ``pt``는 4:3의 비율을 갖습니다. ( 16px = 12pt )

=== font-family
``font-family``는 글꼴을 지정하는 속성입니다. +
글꼴의 이름은 '폰트명'이라고 표현하기도 합니다.
[source,css]
.ex)
----
{ font-family: nanumgothic; }
----

폰트명이 한글이거나 폰트명에 공백이 포함되어 있다면, 작은 따옴표(')로 묶어주세요.
[source,css]
.ex)
----
{ font-family: '나눔고딕'; }
{ font-family: '맑은 고딕'; }
{ font-family: 'malgun gothic'; }
----

콤마(,)로 구분하여 여러 글꼴을 지정하는 것도 가능합니다. +
브라우저는 먼저 선언한 순으로 글꼴을 찾습니다.
[source,css]
.ex)
----
{ font-family: '나눔고딕', '맑은 고딕'; }
----

폰트명을 한글과 영문 모두 사용하는 경우에는 한글명 &#8658; 영문명 순으로 적어주세요. +
영문 이름을 적어주는 것은 한글 이름을 인식하지 못하는 경우를 대비하기 위함입니다.
[source,css]
.ex)
----
{ font-family: '나눔고딕', nanumgothic; }
----

마지막에는 먼저 선언한 글꼴의 타입에 따라 ``serif``, `sans-serif` 중 한가지 글꼴 타입을 적어주세요. +
선언한 글꼴을 찾지 못할 경우 비슷한 글꼴을 찾는데 도움을 줍니다.
[source,css]
.ex)
----
{ font-family: '나눔고딕', nanumgothic, '맑은 고딕', 'malgun gothic', sans-serif; }
----

=== line-height
``line-height``는 행간을 지정하는 속성입니다. +
단위는 ``px``, ``em``, ``%``를 사용할 수 있고, 단위 없이 숫자만 적용할 수도 있습니다.
[source,css]
.ex)
----
{ font-size: 12px; line-height: 18px; }
{ font-size: 12px; line-height: 1.5em; } /* 12px * 1.5em = 18px */
{ font-size: 12px; line-height: 150%; } /* 12px * 150% = 18px */
{ font-size: 12px; line-height: 1.5; } /* 12px * 1.5 = 18px */
----
NOTE: ``line-height``에 단위를 적용하면 계산된 수치가 상속되지만, 단위를 적용하지 않을 경우엔 수식이 상속됩니다.

=== font
``font-style``, ``font-family``, ``font-size``, ``font-family``, ``line-height`` 속성을 ``font`` 속성으로 축약할 수 있습니다.
[source,css]
.ex)
----
{ font-size: italic bold 12px/18px '나눔고딕'; }
----

== text styles

=== text-align
``text-align``은 ``left``, ``right``, ``center``, `justify` 속성값을 갖습니다. +
텍스트를 정렬하기 위해서는 공간이 필요하기 때문에 ``text-align`` 속성은 ``block``의 성질을 가지고 있는 요소에만 적용할 수 있습니다.
[source,css]
.ex)
----
{ text-align: left; } /* 왼쪽 정렬 */
{ text-align: right; } /* 오른쪽 정렬 */
{ text-align: center; } /* 가운데 정렬 */
{ text-align: justify; } /* 양쪽 정렬 */
----

=== text-indent
``text-indent`` 속성은 들여쓰기(or 내어쓰기)를 지정하기 위한 속성입니다.
[source,css]
.ex)
----
{ text-indent: 10px; } /* 들여쓰기 */
{ text-indent: -10px; } /* 내어쓰기 */
----

=== text-decoration
``text-decoration``은 텍스트를 꾸미기 위한 속성입니다. +
``underline``, ``overline``, ``line-through``, ``none`` 속성값을 사용할 수 있습니다.
[source,css]
.ex)
----
{ text-decoration: underline; } /* 밑줄 */
{ text-decoration: overline; } /* 윗줄 */
{ text-decoration: line-through; } /* 취소선 */
{ text-decoration: underline overline line-through; } /* 밑줄, 윗줄, 취소선 모두 적용 */
{ text-decoration: none; } /* 꾸미기 없음(기본값) */
----

=== letter-spacing
``letter-spacing``은 글자와 글자 사이의 간격을 조정하는 속성입니다. +
``px`` 단위를 사용하며, 양수와 음수 모두 사용 가능합니다.
[source,css]
.ex)
----
{ letter-spacing: -1px; }
----

=== word-spacing
``word-spacing``은 단어와 단어 사이의 간격을 조정하는 속성입니다. +
``px`` 단위를 사용하며, 양수와 음수 모두 사용 가능합니다.
[source,css]
.ex)
----
{ word-spacing: -1px; }
----

=== white-space
``white-space``은 ``normal``, ``nowrap``의 속성값을 갖습니다. +
``normal``은 기본값이며, ``nowrap``을 적용할 경우 글자가 강제로 줄바꿈 되지 않습니다.
[source,css]
.ex)
----
{ white-space: normal; } /* 기본값 */
{ white-space: nowrap; } /* 줄바꿈 하지 않음 */
----

== Boxes
박스 관련 속성들입니다.

=== width
영역의 너비를 지정합니다.

=== height
영역의 높이를 지정합니다.

=== margin
영역간의 간격을 지정합니다.

* margin-top
* margin-right
* margin-bottom
* margin-left

=== padding
영역의 여백을 지정합니다.

* padding-top
* padding-right
* padding-bottom
* padding-left

=== border
테두리를 지정합니다.

* border-width
* border-style
* border-color

=== box-sizing
박스 모델의 계산 방식을 지정합니다.

* border-box
* content-box

== Layout

=== position
* relative
* absoute
* fixed
* static

=== float
* left
* right
* none

=== clear
* left
* right
* both

[source,css]
.ex)
----
{ display: block; clear: both; content: ''; }
----
